#!/usr/bin/env python3
"""
Simple check of how digests are generated
"""

import os
import sys
import django
from datetime import date, timedelta

# Setup Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'lecturebuzz.settings')
sys.path.append('.')
django.setup()

from accounts.models import User
from reminders.models import Reminder

def check_digest_generation():
    """Check how digests are currently generated"""
    
    print("🔍 DIGEST GENERATION CHECK")
    print("=" * 30)
    
    today = date.today()
    
    # Get all digests for today
    all_digests = Reminder.objects.filter(
        reminder_type='daily_digest',
        digest_date=today
    ).order_by('created_at')
    
    print(f"📝 Total digests for today: {all_digests.count()}")
    
    if all_digests.exists():
        print(f"\n📋 Digest creation details:")
        
        creation_times = []
        
        for digest in all_digests:
            creation_time = digest.created_at
            creation_times.append(creation_time)
            
            print(f"   👤 {digest.student.username}:")
            print(f"      Created: {creation_time.strftime('%I:%M %p')} UTC")
            print(f"      Scheduled: {digest.reminder_time}")
            print(f"      Is sent: {digest.is_sent}")
        
        # Check if all created at same time (batch) or different times (individual)
        unique_times = len(set(creation_times))
        
        print(f"\n📊 Creation pattern:")
        if unique_times == 1:
            print("   ✅ All digests created at SAME time")
            print("   📍 Generated by: Background service or batch process")
            print("   🤖 This means: AUTOMATIC generation")
        else:
            print("   ⚠️  Digests created at DIFFERENT times")
            print("   📍 Generated by: Website visits or individual triggers")
            print("   🌐 This means: Manual/visit-triggered generation")
    
    else:
        print("📭 No digests found for today")

def test_middleware_generation():
    """Test if middleware generates digests"""
    
    print(f"\n🔧 MIDDLEWARE GENERATION TEST")
    print("=" * 35)
    
    # Create test for tomorrow
    tomorrow = date.today() + timedelta(days=1)
    student = User.objects.filter(user_type='student').first()
    
    if not student:
        print("❌ No student found")
        return
    
    # Clear tomorrow's digests
    Reminder.objects.filter(
        student=student,
        reminder_type='daily_digest',
        digest_date=tomorrow
    ).delete()
    
    print(f"🧹 Cleared digests for {tomorrow}")
    
    # Test middleware directly
    from reminders.middleware import AutoDigestMiddleware
    from django.http import HttpResponse
    
    def dummy_response(request):
        return HttpResponse("OK")
    
    middleware = AutoDigestMiddleware(dummy_response)
    factory = RequestFactory()
    request = factory.get('/test/')
    
    # Add session
    SessionMiddleware(dummy_response).process_request(request)
    request.session.save()
    
    print("🔧 Processing request through middleware...")
    response = middleware(request)
    
    # Check if digest was created
    digest_after = Reminder.objects.filter(
        student=student,
        reminder_type='daily_digest',
        digest_date=tomorrow
    ).first()
    
    if digest_after:
        print("✅ Middleware DOES generate digests")
        print(f"   Created digest ID: {digest_after.id}")
    else:
        print("❌ Middleware does NOT generate digests")

def check_background_service_generation():
    """Check if background service generates digests"""
    
    print(f"\n🤖 BACKGROUND SERVICE GENERATION TEST")
    print("=" * 40)
    
    tomorrow = date.today() + timedelta(days=1)
    
    # Count digests before
    digests_before = Reminder.objects.filter(
        reminder_type='daily_digest',
        digest_date=tomorrow
    ).count()
    
    print(f"📝 Digests before service: {digests_before}")
    
    # Run background service for tomorrow
    from django.core.management import call_command
    
    try:
        print("🤖 Running background service...")
        call_command('send_real_daily_digests', date=tomorrow.isoformat())
        
        # Count digests after
        digests_after = Reminder.objects.filter(
            reminder_type='daily_digest',
            digest_date=tomorrow
        ).count()
        
        print(f"📝 Digests after service: {digests_after}")
        
        if digests_after > digests_before:
            print("✅ Background service DOES generate digests")
            print(f"   Generated: {digests_after - digests_before} new digests")
        else:
            print("❌ Background service does NOT generate new digests")
            
    except Exception as e:
        print(f"❌ Background service error: {e}")

if __name__ == "__main__":
    check_digest_generation()
    test_middleware_generation()
    check_background_service_generation()
    
    print(f"\n" + "=" * 50)
    print("🎯 DIGEST GENERATION SUMMARY:")
    print("   📊 Check the results above to understand:")
    print("   • Are digests created automatically?")
    print("   • Are digests created on website visits?")
    print("   • Are digests created by background service?")
    print("   • What triggers digest generation?")