#!/usr/bin/env python
"""
Test web request to trigger middleware
"""

import urllib.request
import urllib.error
from datetime import date

def test_web_request():
    print("🌐 TESTING WEB REQUEST TO TRIGGER MIDDLEWARE")
    print("=" * 50)
    
    # Clear today's digests first
    import os
    import django
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'lecturebuzz.settings')
    django.setup()
    
    from reminders.models import Reminder
    today = date.today()
    
    # Delete today's digests
    deleted = Reminder.objects.filter(digest_date=today).delete()
    print(f"🗑️ Cleared {deleted[0]} existing digests for {today}")
    
    try:
        print(f"📡 Making request to http://127.0.0.1:8000/")
        
        # Make HTTP request
        with urllib.request.urlopen('http://127.0.0.1:8000/', timeout=10) as response:
            content = response.read().decode('utf-8')
            print(f"✅ Request successful! Status: {response.status}")
        
        # Check if digests were created by the middleware
        digests_after = Reminder.objects.filter(
            reminder_type='daily_digest',
            digest_date=today
        )
        
        print(f"\n📊 MIDDLEWARE RESULTS:")
        print(f"📅 Digests created for {today}: {digests_after.count()}")
        
        for digest in digests_after:
            status = "✅ SENT" if digest.is_sent else "⏳ PENDING"
            print(f"   👤 {digest.student.username}: {status}")
            
        if digests_after.count() > 0:
            print(f"\n🎉 SUCCESS! Middleware automatically generated {digests_after.count()} digests!")
        else:
            print(f"\n❌ No digests were generated by middleware")
            
    except urllib.error.URLError as e:
        print(f"❌ Could not connect to server: {e}")
        print(f"💡 Make sure server is running: python manage.py runserver")
    except Exception as e:
        print(f"❌ Error: {e}")

if __name__ == "__main__":
    test_web_request()