# Generated by Django 4.2 on 2025-11-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='reminder',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('scheduled', 'Scheduled Reminder'), ('update', 'Update Notification')], default='scheduled', max_length=20),
        ),
    ]
