# Generated by Django 4.2 on 2025-11-23 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_schedule_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reminders', '0002_alter_reminder_options_reminder_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='digest_date',
            field=models.DateField(blank=True, help_text='Date for daily digest', null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('scheduled', 'Scheduled Reminder'), ('update', 'Update Notification'), ('daily_digest', 'Daily Schedule Digest')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='schedules.schedule'),
        ),
        migrations.CreateModel(
            name='DailyDigestPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest_time', models.CharField(choices=[('06:00', '6:00 AM - Early Morning'), ('07:00', '7:00 AM - Morning'), ('08:00', '8:00 AM - Before Classes'), ('20:00', '8:00 PM - Evening (Next Day)'), ('21:00', '9:00 PM - Night (Next Day)')], default='07:00', max_length=5)),
                ('is_enabled', models.BooleanField(default=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digest_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
