# Generated by Django 4.2 on 2025-12-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_reminder_digest_date_alter_reminder_reminder_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydigestpreference',
            name='digest_time',
            field=models.CharField(choices=[('06:00', '6:00 AM - Early Morning'), ('07:00', '7:00 AM - Morning'), ('08:00', '8:00 AM - Before Classes'), ('09:00', '9:00 AM - Mid Morning'), ('10:00', '10:00 AM - Late Morning'), ('12:00', '12:00 PM - Noon'), ('13:00', '1:00 PM - Early Afternoon'), ('14:00', '2:00 PM - Afternoon'), ('15:00', '3:00 PM - Mid Afternoon'), ('16:00', '4:00 PM - Late Afternoon'), ('17:00', '5:00 PM - Evening Start'), ('18:00', '6:00 PM - Evening (Next Day)'), ('19:00', '7:00 PM - Evening (Next Day)'), ('20:00', '8:00 PM - Evening (Next Day)'), ('21:00', '9:00 PM - Night (Next Day)'), ('22:00', '10:00 PM - Late Night (Next Day)')], default='07:00', max_length=5),
        ),
    ]
