# Generated by Django 4.2 on 2025-12-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_alter_dailydigestpreference_digest_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydigestpreference',
            name='digest_time',
            field=models.TimeField(default='07:00', help_text='Choose any time for your daily digest email'),
        ),
    ]
