# Generated by Django 4.2 on 2025-12-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturerprofile',
            name='subjects',
            field=models.TextField(blank=True, help_text='Subjects taught (comma-separated, e.g., Data Structures, Database Management)', null=True),
        ),
    ]
