# Generated by Django 4.2 on 2025-12-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_schedule_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day_order',
            field=models.CharField(blank=True, choices=[('1', 'Day 1'), ('2', 'Day 2'), ('3', 'Day 3'), ('4', 'Day 4'), ('5', 'Day 5'), ('6', 'Day 6')], help_text='Day order (Day 1, Day 2, etc.)', max_length=1, null=True),
        ),
    ]
